// CS2SX Stub — wird nicht transpiliert, nur für IntelliSense

public class Form
{
    public void Add(Control control)
    {
    }
}

public abstract class Control
{
    public int X
    {
        get; set;
    }
    public int Y
    {
        get; set;
    }
    public int Width
    {
        get; set;
    }
    public int Height
    {
        get; set;
    }
    public bool Visible { get; set; } = true;
}

public abstract class SwitchApp
{
    public Form Form { get; } = new Form();
    public virtual void OnInit()
    {
    }
    public virtual void OnFrame()
    {
    }
    public virtual void OnExit()
    {
    }
}

public class Label : Control
{
    public string Text { get; set; } = "";
    public Label(string text) => Text = text;
}

public class Button : Control
{
    public string Text { get; set; } = "";
    public bool Focused
    {
        get; set;
    }
    public Action OnClick { get; set; } = () => { };
    public Button(string text) => Text = text;
}

public class ProgressBar : Control
{
    public int value
    {
        get; set;
    }
    public int width_chars
    {
        get; set;
    }
    public ProgressBar(int widthChars) => width_chars = widthChars;
}


// Auto-generated by CS2SX — do not edit manually
// Diese Stubs erlauben dem C#-Compiler CS2SX-Projekte zu validieren.
// Zur Laufzeit werden sie vom Transpiler zu libnx-C-Code übersetzt.

namespace CS2SX.Switch
{


    // ── File I/O ──────────────────────────────────────────────────────────────

    public static class File
    {
        public static string ReadAllText(string path) => "";
        public static void WriteAllText(string path, string content)
        {
        }
        public static void AppendAllText(string path, string content)
        {
        }
        public static bool Exists(string path) => false;
        public static void Delete(string path)
        {
        }
        public static void Copy(string src, string dst)
        {
        }
    }

    public static class Directory
    {
        public static bool Exists(string path) => false;
        public static void CreateDirectory(string path)
        {
        }
        public static void Delete(string path)
        {
        }
        public static string[] GetFiles(string path) => System.Array.Empty<string>();
        public static string[] GetFiles(string path, string pattern) => System.Array.Empty<string>();
        public static string GetCurrentDirectory() => "/switch";
        public static System.Collections.Generic.IEnumerable<string>
                               EnumerateFiles(string path) => System.Array.Empty<string>();
    }
}

// Parse-Stubs — werden vom Transpiler zu CS2SX_Int_Parse etc. übersetzt

public static class IntParser
{
    // Stubs damit der C#-Compiler int.Parse akzeptiert —
    // int und float sind Schlüsselwörter und können keine statischen Methoden haben,
    // daher sind diese Stubs nur für die Transpiler-Erkennung nötig.
    // Der Transpiler erkennt "int.Parse" direkt als calleeStr.
}